### ISSUE TITLE
Creating an Ok result without a value

### ISSUE THREAD

**Issue by wvteijlingen** [vultix/ts-results#1]
It seems currently impossible to create an Ok result without any value. This could be useful if a function does not return a value, but can still return an error. Is this not possible, or am I missing something?

Example:

```typescript
function foo(isOk: boolean): Result<void, Error> {
  if(isOk) {
    return new Ok()
  } else {
    return new Err(new Error("Is is not ok"))
  }
}
```

**Comment by vultix** [comment]
I've been looking into possible solutions for `void` in Results, and everything I have come up with feels super kludgy and doesn't work well in all situations.

I'm open to suggestions for how to get this to work:
```typescript
class Ok<T> {
  constructor(public val: T) {
  }
}
const ok = new Ok<void>();
```

So, instead I'll offer a few alternatives:
```typescript
// You could use anything in place of the null.  boolean, a number, string, etc...
function foo(isOk: boolean): Result<null, Error> {
  if(isOk) {
    return new Ok(null)
  } else {
    return new Err(new Error("Is is not ok"))
  }
}
```


```typescript
function foo(isOk: boolean): Err<Error> | undefined {
  if (!isOk) {
    return new Err(new Error("Is is not ok"));
  }
}
```

**Comment by wvteijlingen** [comment]
Yeah, I've been looking at it as well, and didn't find a suitable solution either.

The best I could come up with is to create two additional types: `OkWithoutValue` and `ResultWithoutValue` (or however you want to name them). That would support all the type checking, and makes it clear to the user that there is no actual success value.

**Comment by vultix** [comment]
I've added a new static EMPTY field to both Err and Ok that hold their respective void values.  That should solve this until typescript gives us a better option.

Thanks for the issue!

**Comment by JarekToro** [comment]
Was looking into something similar. I landed on something like this and figured I'd share
[Typescript Playground Link](https://www.typescriptlang.org/play?#code/MYGwhgzhAEDyDWAeAKtAvNAbgewJYBMA+aAbwChpoAHAVwCMRdgswRoAuaVAUwA8AXbgDt8MHAWgB+aEO6ZuAJw5cK0YNiER+CmsH7YFACkytJnAKK9QNfNxQAacUQCUpVZVwAzaMdbPylIHQ-AAWuBAAdCZsGNHu0AC+3CAQ3G5BlKHhUazo0DQi3J64svjQkDJyivEJqrW16pr80NjwebIA7nDwhs4A3GStOWwA9COV8gpkZI1aLfAAytolAObt3F0IhgDkglrb-YOLy0Irw9Bj0FoKq0A)
```ts
  
class Ok<T = void> {
  public val : T extends void ? never : T
  constructor(val?: Exclude<T,void>) {
    if (val){
      this.val = val
    }else {
      this.val = undefined as never
    }
  }
}
const ok = new Ok();
ok.val // never

const okString = new Ok('test');
okString.val // string
```
