### ISSUE TITLE
Adding flatMap

### ISSUE THREAD

**Issue by GabrielCTroia** [vultix/ts-results#12]
I often find myself chaining a bunch of results together and expect/wish they simply unwrap similar to a Promise, but of course that's not how Result's map works. Which is why I believe **flatMap** could help out.

Here's an example:
```
getUser({id: 3})
  .map((user) => getUserVehicle(user))
  .map((vehicleResult) => {
     // Vehicle here is a Result not the unwapped value, 
     //  therefore I need to unwrap it again, which creates a more difficult control flow

    vehicleResult
      .mapErr((error) => {
         // handle the error
      })
      .map((vehicle) => {
        // do stuff with the vehicle now
      })
  })
```

It would be great if instead we could do 
```
getUser({id: 3})
  .flatMap((user) => getUserVehicle(user.id))
  .map((vehicle) => {
     // do stuff with the vehicle right here
  })
```

**Comment by vultix** [comment]
After discussing this on the associated pull request, would you agree that `andThen` handles this well enough?  Are we ok to close this Issue and PR?

**Comment by GabrielCTroia** [comment]
Hey, yeah – we should close it but I had one question in my PR:

**"Is the difference that andThen() would act more like a finally() where both mapErr and map would end up calling it?"**

If that isn't so, and there isn't any difference my only suggestion would be to have an alias "andThen" -> "flatMap". That's only since I believe more people are familiar with the "flatMap" naming convention than "andThen".

**Comment by vultix** [comment]
Closing in favor of using `andThen()`.
