### ISSUE TITLE
Include Option<T>

### ISSUE THREAD

**Issue by petehunt** [vultix/ts-results#16]
hey, thanks for the great library. i have an internal fork that adds an `Option<T>` type that's compatible with `Result<Ok, Err>` type already in here. would you want this included in this library? i'm happy to send it as a PR.

thanks!

**Comment by vultix** [comment]
@petehunt I think that would be awesome, thank you!  

Do you think the option should be in a new npm package? `ts-results` and `ts-options`?

I'm leaning towards keeping it in one package as `import {Result, Option} from 'ts-results'` feels simpler.

**Comment by petehunt** [comment]
i was thinking just 1 package. will send ya a PR and you can let me know what you think!

**Comment by vultix** [comment]
Just published a release for this! Checkout the [README](https://github.com/vultix/ts-results#option-example) and [CHANGELOG](https://github.com/vultix/ts-results/blob/master/CHANGELOG.md#v310) for examples.
