### ISSUE TITLE
Add methods for converting between Result and Option

### ISSUE THREAD

**Issue by messier102** [vultix/ts-results#25]
Hi there, thanks for a very useful library. As a small quality of life improvement, it would be nice to have a couple methods to convert Results to Options and vice versa. So something like

```ts
// foo: Result<T, E>
const bar: Option<T> = foo.ok ? foo.val : None;
```

could be replaced with

```ts
const bar: Option<T> = foo.to_option()
```

and conversely

```ts
// foo: Option<T>
const bar: Result<T, E> = foo.to_result(Err("some error"));
```

For reference, here are the same methods in Rust: 
- https://doc.rust-lang.org/std/option/enum.Option.html#method.ok_or
- https://doc.rust-lang.org/std/result/enum.Result.html#method.ok

**Comment by vultix** [comment]
This was just released in ts-results 3.3.0!
