### ISSUE TITLE
Issues with type narrowing in if-else statements

### ISSUE THREAD

**Issue by abhayvatsa** [vultix/ts-results#28]
Hi there!

Thanks for making this, been enjoying this library.  

I am running into an issue with the type narrowing for if-else statements. I'm not sure if I'm doing something wrong, but this issue was mentioned in #5. I expect that a type guard on `result.ok` would narrow the union type appropriately in the else block. Instead I see an error like this: 
`Type 'string | number' is not assignable to type 'string'. Type 'number' is not assignable to type 'string'.`

Currently on typescript 4.2.4

Here are two examples that are more or less the same.

```typescript
import { Ok, Err } from 'ts-results'

const result = Ok(1) as Ok<number> | Err<string>

if (result.ok) {
  const val: number = result.val
} else {
  const val: string = result.val
}
```

```typescript
import { Ok, Result } from 'ts-results'

const result = Ok(1) as Result<number, string>

if (result.ok) {
  const val: number = result.val
} else {
  const val: string = result.val
}
```

**Comment by vultix** [comment]
Alright, I think I've tracked this one down.  As far as I can tell, the type narrowing only works when `strictNullChecks` is turned on in your tsconfig file.

Will you try turning on `strictNullChecks` and let me know if that fixes the issue?  I'm guessing this is a bug in the typescript compiler itself

**Comment by vultix** [comment]
Here's a super simple replication in the [typescript playground](https://www.typescriptlang.org/play?strictNullChecks=false#code/JYOwLgpgTgZghgYwgAgPIGtkG8BQz-ID26AXMmFAK4QDceBAbnADZkDOFoA5nQL445QkWIhQBRKFGz18xMvGZtaM5E1bIJUQlD4CAJhATM4UFAkIgOyUBzIZkAHw2S6gmMgAUNsADpiASmkCZHNLMGQ4dk4QLmQAXmswnzU+ZAhFFFxg0KsAIzJNbXjEjmSWPiA)

**Comment by vultix** [comment]
Looks like this is a known bug: https://github.com/microsoft/TypeScript/issues/10564

**Comment by abhayvatsa** [comment]
@vultix. Wow, thanks this worked. Appreciate the fast response. Would it make sense to make a note of this somewhere in the docs?

**Comment by vultix** [comment]
I added a note in the README.  I'm going to close this issue for now, hopefully this gets fixed in Typescript soon
