### ISSUE TITLE
Can I create a Err / Ok without new?

### ISSUE THREAD

**Issue by Jack-Works** [vultix/ts-results#3]
The new operator seems doesn't important

**Comment by vultix** [comment]
Sadly, ES6 requires the new operator when creating classes.  I'd agree it's slightly less ergonomic, but I was unable to come up with suitable workarounds that provide all of these functions:

- Creation without new operator: `const result = Err(e);`
- Separation of Err and Ok types: `function handleOk(val: Ok<string>);`
- `instanceof` checks: `result instanceof Err`

**Comment by Jack-Works** [comment]
Can do via a Proxy

![image](https://user-images.githubusercontent.com/5390719/73783799-4171c980-47cf-11ea-8f8e-026bc17940a7.png)

**Comment by Jack-Works** [comment]
> instanceof checks: result instanceof Err

You can do it.
![image](https://user-images.githubusercontent.com/5390719/80947966-cd71ac80-8e23-11ea-94c6-67b4a58230d6.png)
