### ISSUE TITLE
tslib is required dependency in ts-results

### ISSUE THREAD

**Issue by datapain** [vultix/ts-results#32]
Hello,

Unfortunately, your package used a tslib in the main script:

```javascript
(function (factory) {
    if (typeof module === "object" && typeof module.exports === "object") {
        var v = factory(require, exports);
        if (v !== undefined) module.exports = v;
    }
    else if (typeof define === "function" && define.amd) {
        define(["require", "exports", "tslib", "./result", "./option"], factory);
    }
})(function (require, exports) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    var tslib_1 = require("tslib");
    tslib_1.__exportStar(require("./result"), exports);
    tslib_1.__exportStar(require("./option"), exports);
});
//# sourceMappingURL=index.js.map
```

But this dependency isn't listed as such.

For example, you don't have any dependency :)

it's easy to reproduce:
```bash
$: mkdir test-project && test-project
$: npm init -y && npm i --save ts-results
$: touch main.js
$: echo "require('ts-results').Ok()" > main.js
$: node main.js
```

Error output is:
```
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'tslib'
Require stack:
- /*********/github/test-project/node_modules/ts-results/index.js
```

How it affects one of my projects after my typescript build and pruning the production dependencies I tried to ran and got this error too. Because after my builds I don't have a tslib as shadow dependency.

and it makes me sad.

Please, fix that or add tslib as dependency <3

Best regards

**Comment by iamdavidmartin** [comment]
The problem is

1. tsconfig.json has importHelpers set to true. Setting to false removes tslib as a dependency.
2. package.json is missing "main":"dist/index.js"

In my repo, I've fixed those two things: https://github.com/iamdavidmartin/ts-results

However, I've also added dist/ in the repo and I also removed dist/ from .gitignore. Why? So I could just include it in my project and move on.

**Comment by nicholasf** [comment]
As above.

**Comment by petehunt** [comment]
unfortunately i've had to remove `ts-results` from a recent project due to this issue :/ hopefully we can get this fixed soon @vultix
