### ISSUE TITLE
TS2349: This expression (Result<?, ?>.else) is not callable

### ISSUE THREAD

**Issue by Jack-Works** [vultix/ts-results#4]
Code:
```ts
declare function work(): Result<boolean, void>
work().else(true)
// And I think it should accept a function as well `.else(() => heavyWork())`
```

Error:
```
(property) else: (<T2>(val: T2) => boolean) | (<T2>(val: T2) => T2)

This expression is not callable.

Each member of the union type
        '(<T2>(val: T2) => boolean) | (<T2>(val: T2) => T2)' has signatures,
but none of those signatures are compatible with each other.(2349)
```
[Playground link](https://www.typescriptlang.org/play/?target=6&ssl=1&ssc=1&pln=46&pc=1#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXwHccYBrACgEoAueAJRAGdkIMAeAIxxwhClQBp4ANxxZgAPgCwAKCKlKAOhAQGIMhhjIQFGTJAAPAA7EM8UJFgILDBvACiMGKzvj4Abxnwv8OFGB4IAE9hKAgaOwBuT28GDChsMB9ef1Qg+wBZAAUAFQBNcMdWETFxKOlvJL8A4JwSeABeJFDVMorfFLSQRwb4DS1W7zA8WM1MYjIhUPCKAa8AegAqBejvBfgASURegAsEOCYWeG2oWygQiC0kjGQYVFsMY9NJi5AFLwB5B66CLFUrm7uOwQhhOqmA8Cw+GeWgUKy8awAAiCYFAALbnIHnS4YHBJQzQMAIL7wLowYiELAPOHwBZzOHKVSsbIAJnEEym8BZ1E5zNmJKM4AwZFRDAA5jQRpDRdzUCAhF0+WgCCjDJQaLL5TA+aioIYmazhbrDF0aOywvANV0KA1XFyCk4XNrdQ4HQadYZjTBTaTpjb7MzuS7nKyygBfPRGExmcDQODway2d4kJmuDzlbztarnGjZPmxeJYRKZ1LBOxZPI0JNFUQSPnFtK1Hp9EB15JZ0k9RDNFtwoZ3PpjGBmnMzOGLZbp1YbLbE-bMUzHU5YvYga63e6PZdveCfXYwH5-OBrwHEkE2EDgyFb6mI5FojHE6FE3FwfFQQmY0nkn5Uyfwul-gyID6myzw5gGOZ8gYxqYMKYoShoUrcrmcJKiqaqck6eosmy7qeqaYGcta9S2hBO7JjhWFBnYbpGia8BkD6Fpylafo0dyVbZKUMjhtI0FRuYsZEoExp0Iw85MoILg9GQnGuAAPvYhQuNaABk7hwu6IGGh69HDkRfp2mJBxsCyUncX+7rUbRulegxhF2MRrjsTQ9AmZJ-oWaGZT8TApiCZYvQiQgbnzkm2TBUy-IYCAqDALYoUsKwfCBIIKXiK4jTZNFsXxcZEmQogXTwAAqmlqCBK4AD8pXwOqLFahGxh+dGFhxhgwX5SwLoRcaUUGDFcUJeJSUpeVlWZZyOVDV1bBjRCqBFTApXVbV9Waj5kYtQFcYoOg2B4LNDBMgAjFJZ08lJBpziwJ2uSNpkXXYJ3iIIN0YMy93uWZnncolbAANrZBdLIALrnfAik0RZvn+TGgV7ZguD4P9x3A+dgg-TRmMAMxSTjbLvXds2nedr1JCZn0k1jrJvQ9ONfRJ2R4-YBN-Q9rBAyDzK4+D9gnZD-qC3YBObc1cNtQgiMHSjD1o093NXbj+OYwALFJquEw9xP-aT-Pk+9VO6zTBv04zSXM-jpsmar5umer9ia+z7lc5jPOciz2Sq3zz3C8yws48LmtiwJ8O7WgSOHajZAKLH70MHbyUVeN4gA6DzsSSlacp2UQA)

**Comment by vultix** [comment]
I'd be more than willing to accept a PR for this change.

**Comment by GabrielCTroia** [comment]
I'm not sure how the `else` method was initially thought but it doesn't seem to work at all. I know this is more of a typescript issue [33591](https://github.com/microsoft/TypeScript/issues/33591) or [7294](https://github.com/microsoft/TypeScript/issues/7294), but imho the else functionality should either be removed or a workaround found.

This being said I'd more than willing to give it a try once I get some time.

**Comment by Jack-Works** [comment]
I found a fix for this. Please wait
