### ISSUE TITLE
.map works strange

### ISSUE THREAD

**Issue by Jack-Works** [vultix/ts-results#8]
I have two functions:

```ts
extractTextFromTypedMessage(x: Message | null): Result<string, E1>
shouldActivate(post: string): Result<void, E2>
```

Then I write
```
extractTextFromTypedMessage(post).map(shouldActivate)
```

What I expect is unpack the map returned by should activate:
```
Result<void, E1 | E2>
```

But it finally returns
```
Result<Result<void, E2>, E1>
```

**Comment by tom-sherman** [comment]
This requires the `and_then` method from Rust. `.map` should return a new T, not a new Result<T, E>

**Comment by Jack-Works** [comment]
I already added the method I need in that PR
